### ISSUE TITLE
Review Terminology Document

### ISSUE THREAD

**Issue by techrebelgit** [Tico4Chain-Coders/Trustless-Work#7]
I made this to clarify terminology for future reference: 
https://www.notion.so/tech-rebel/Terminology-for-Trustless-Work-51189d60e9d546bcb574c18bfdf14e5f?pvs=4

Please review, comment and approve.

**Comment by armandocodecr** [comment]
The only comment I have to this technical documentation is that in the workflow example it should be mentioned that when depositing funds to the milestone contract, what is deposited is half of what it is worth to complete it. When it is completed and approved by the customer, the other half is transferred.

**Comment by techrebelgit** [comment]
New Version: 
https://tech-rebel.notion.site/Terminology-51189d60e9d546bcb574c18bfdf14e5f?pvs=4

**Comment by JoelVR17** [comment]
@techrebelgit thanks a lot for this document. It will help me a lot with the API doc.
